const $=id=>document.getElementById(id);const KEY='miNutricionV1';
let state={profile:{},history:[],water:{date:'',ml:0}};
const today=()=>new Date().toISOString().slice(0,10);const round=n=>Math.round(n);
function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}; if(state.water.date!==today())state.water={date:today(),ml:0}; fill();render()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fill(){const p=state.profile;['sex','age','height','weight','targetWeight','targetDate','bodyFat','activity','goal','proteinFactor','fatFactor'].forEach(k=>{if(p[k]!==undefined)$(k).value=p[k]});$('logDate').value=today()}
function calc(){const p=state.profile,w=+p.weight,h=+p.height,a=+p.age;if(!w||!h||!a)return null;const bmr=10*w+6.25*h-5*a+(p.sex==='male'?5:-161),tdee=bmr*+p.activity;const adjust={maintain:0,loseSlow:-300,lose:-500,gain:250}[p.goal]||0;const calories=Math.max(1200,round(tdee+adjust));const protein=round(w*(+p.proteinFactor||2)),fat=round(w*(+p.fatFactor||.9));const carbs=Math.max(0,round((calories-protein*4-fat*9)/4));return{bmr:round(bmr),tdee:round(tdee),calories,protein,fat,carbs,bmi:(w/((h/100)**2)).toFixed(1)}}
function render(){const c=calc(),p=state.profile;if(c){$('calTarget').textContent=c.calories;$('bmr').textContent=c.bmr;$('tdee').textContent=c.tdee;$('bmiValue').textContent=c.bmi;$('protein').textContent=c.protein+' g';$('fat').textContent=c.fat+' g';$('carbs').textContent=c.carbs+' g';$('weightDiff').textContent=p.targetWeight?(+p.targetWeight-+p.weight).toFixed(1):'--';$('goalSummary').textContent={maintain:'Mantención estimada',loseSlow:'Déficit moderado estimado',lose:'Déficit estimado',gain:'Superávit estimado'}[p.goal];pace();water()}history();chart()}
function pace(){const p=state.profile;if(!p.targetDate||!p.weight||!p.targetWeight){$('paceMessage').textContent='';return}const days=Math.ceil((new Date(p.targetDate+'T12:00:00')-new Date())/864e5),diff=+p.targetWeight-+p.weight;if(days<=0){$('paceMessage').textContent='La fecha objetivo debe ser posterior a hoy.';return}const weekly=Math.abs(diff)/(days/7);$('paceMessage').textContent=`Para llegar a ${p.targetWeight} kg en ${days} días, la variación promedio sería ${weekly.toFixed(2)} kg/semana. Es solo una proyección matemática, no una recomendación clínica.`}
$('profileForm').addEventListener('submit',e=>{e.preventDefault();const p={};['sex','age','height','weight','targetWeight','targetDate','bodyFat','activity','goal','proteinFactor','fatFactor'].forEach(k=>p[k]=$(k).value);state.profile=p;const existing=state.history.find(x=>x.date===today());if(existing)existing.weight=+p.weight;else state.history.push({date:today(),weight:+p.weight});save();render()});
function water(){const goal=round((+state.profile.weight||0)*35);$('waterAmount').textContent=state.water.ml;$('waterGoal').textContent='Meta sugerida: '+(goal||'--')+' ml';$('waterBar').style.width=(goal?Math.min(100,state.water.ml/goal*100):0)+'%'}
$('plusWater').onclick=()=>{state.water.ml+=250;save();water()};$('minusWater').onclick=()=>{state.water.ml=Math.max(0,state.water.ml-250);save();water()};$('resetWater').onclick=()=>{state.water.ml=0;save();water()};
$('weightForm').addEventListener('submit',e=>{e.preventDefault();const d=$('logDate').value,w=+$('logWeight').value;const x=state.history.find(x=>x.date===d);x?x.weight=w:state.history.push({date:d,weight:w});state.profile.weight=w;$('weight').value=w;save();render();$('logWeight').value=''});
function history(){const el=$('historyList');el.innerHTML='';[...state.history].sort((a,b)=>b.date.localeCompare(a.date)).forEach(x=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<span>${new Date(x.date+'T12:00:00').toLocaleDateString('es-CL')}</span><strong>${x.weight.toFixed(1)} kg</strong><button aria-label="Eliminar">Eliminar</button>`;d.querySelector('button').onclick=()=>{state.history=state.history.filter(y=>!(y.date===x.date&&y.weight===x.weight));save();render()};el.appendChild(d)})}
function chart(){const cv=$('weightChart'),ctx=cv.getContext('2d'),data=[...state.history].sort((a,b)=>a.date.localeCompare(b.date));ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#667875';ctx.font='24px sans-serif';if(data.length<2){ctx.fillText('Registra al menos 2 pesos para ver la tendencia.',35,190);return}const pad=55,min=Math.min(...data.map(x=>x.weight))-1,max=Math.max(...data.map(x=>x.weight))+1;ctx.strokeStyle='#dce7e5';for(let i=0;i<5;i++){const y=pad+i*(cv.height-2*pad)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(cv.width-pad,y);ctx.stroke()}ctx.strokeStyle='#0f766e';ctx.lineWidth=6;ctx.beginPath();data.forEach((x,i)=>{const px=pad+i*(cv.width-2*pad)/(data.length-1),py=cv.height-pad-(x.weight-min)/(max-min)*(cv.height-2*pad);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();data.forEach((x,i)=>{const px=pad+i*(cv.width-2*pad)/(data.length-1),py=cv.height-pad-(x.weight-min)/(max-min)*(cv.height-2*pad);ctx.fillStyle='#14b8a6';ctx.beginPath();ctx.arc(px,py,8,0,Math.PI*2);ctx.fill()})}
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mi-nutricion-respaldo-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').addEventListener('change',async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj.profile||!Array.isArray(obj.history))throw Error();state=obj;save();fill();render();alert('Respaldo importado correctamente.')}catch(err){alert('El archivo no es un respaldo válido de Mi Nutrición.')}});
let deferred;$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('installBtn').classList.add('hidden')}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').classList.remove('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();
